SELECT DISTINCT ?player ?playerLabel
  (GROUP_CONCAT(DISTINCT ?firstnameLabel; SEPARATOR="; ") as ?firstnameLabels)
  (GROUP_CONCAT(DISTINCT ?lastnameLabel; SEPARATOR="; ") as ?lastnameLabels)
  ?sexLabel 
  (MAX(?dob) AS ?dobMax) (CONCAT(STR(YEAR(?dobMax)),"-",STR(MONTH(?dobMax)),"-",STR(DAY(?dobMax))) AS ?dobFormat)
  (GROUP_CONCAT(DISTINCT ?pobLabel; SEPARATOR="; ") as ?pobLabels)
  (MAX(?dod) AS ?dodMax) (CONCAT(STR(YEAR(?dodMax)),"-",STR(MONTH(?dodMax)),"-",STR(DAY(?dodMax))) AS ?dodFormat)
  (GROUP_CONCAT(DISTINCT ?podLabel; SEPARATOR="; ") as ?podLabels)
  (GROUP_CONCAT(DISTINCT ?citizenshipLabel; SEPARATOR="; ") as ?citizenshipLabels)
  (GROUP_CONCAT(DISTINCT ?sportCountryLabel; SEPARATOR="; ") as ?sportCountryLabels)
  (GROUP_CONCAT(DISTINCT ?positionLabel; SEPARATOR="; ") as ?positionLabels)
  (GROUP_CONCAT(DISTINCT ?careerStartYear; SEPARATOR="; ") as ?careerStartYears)
  (GROUP_CONCAT(DISTINCT ?careerEndYear; SEPARATOR="; ") as ?careerEndYears)
  (GROUP_CONCAT(DISTINCT ?mass; SEPARATOR="; ") as ?masses)
  (GROUP_CONCAT(DISTINCT ?height; SEPARATOR="; ") as ?heights)
  (GROUP_CONCAT(DISTINCT ?ESPNscrumID; SEPARATOR="; ") as ?ESPNscrumIDs)
  (GROUP_CONCAT(DISTINCT ?AllRugbyID; SEPARATOR="; ") as ?AllRugbyIDs)
  (GROUP_CONCAT(DISTINCT ?GoogleKnowlID; SEPARATOR="; ") as ?GoogleKnowlIDs)
  (GROUP_CONCAT(DISTINCT ?ItsRugbyID; SEPARATOR="; ") as ?ItsRugbyIDs)
  (GROUP_CONCAT(DISTINCT ?RugbyDatabaseID; SEPARATOR="; ") as ?RugbyDatabaseIDs)
WHERE
{ #BIND(wd:Q3470454 AS ?player)
  
#   ?player wdt:P106 wd:Q14089670;                   # P106=occupation, Q14089670=Rugby Union player
#           wdt:P54/wdt:P31 wd:Q43009164.	           # P54=member of sport team, P31=instance of, Q43009164=Rugby Union club
# #           wdt:P54 wd:Q599903.	                   # alt: P54=member of sports team, Q599903=Ireland national rugby union team
  
#   ?player wdt:P106 wd:Q14089670;                   # P106=occupation, Q14089670=Rugby Union player
#           wdt:P54/wdt:P31/wdt:P279* wd:Q14645593.  # P54=member of sport team, P31=instance of, P279=subclass of, Q43009164=Rugby union team
#   ?player wdt:P54/wdt:P31 ?clubType.                                          # P31=instance of
#   FILTER(?clubType IN(
#                       wd:Q14645593,                                 # Q14645593=Rugby Union team
#                       wd:Q43009164,                                 # Q43009164=Rugby Union club
#                       wd:Q63171169,                                 # Q63171169=rugby union franchise
#                       wd:Q63171186,                                 # Q63171186=defunct rugby union club
# #                     wd:Q113144812,                                # Q113144812=women's rugby union club
#                       wd:Q58840819                                  # Q58840819=national rugby union team
#                     ))
  
  
  # get the rugby teams (more general category)
  {    
    ?club wdt:P31 wd:Q14645593.                                     # P31=instance of, Q14645593=Rugby union team
  }
  UNION
  # add the clubs and franchises (more specific categories)
  {
    ?club wdt:P31/wdt:P279* wd:Q14645593.                           # P31=instance of, P279=subclass of, Q14645593=Rugby union team
  }
  # filter depending on team type
  ?club wdt:P31 ?clubType.                                          # P31=instance of
  FILTER(?clubType IN(
                      wd:Q14645593,                                 # Q14645593=Rugby Union team
                      wd:Q43009164,                                 # Q43009164=Rugby Union club
                      wd:Q63171169,                                 # Q63171169=rugby union franchise
                      wd:Q63171186,                                 # Q63171186=defunct rugby union club
#                     wd:Q113144812,                                # Q113144812=women's rugby union club
                      wd:Q58840819                                  # Q58840819=national rugby union team
                    ))
  
#   # the club must have an affiliation
#   ?club wdt:P1416 ?affiliation.                                     # P1416=affiliation
#   ?affiliation wdt:P641 ?affSport.                                  # P641=sport
#   FILTER(!BOUND(?affSport) || ?affSport = wd:Q5849)                 # Q5849=Rugby Union (keep sport-less and rugby affiliations)
#   # the club must participate in a competition
#   ?club wdt:P118 ?competition.                                      # P118=league or competition
#   ?competition wdt:P641 ?competSport.                               # P641=sport
#   FILTER(!BOUND(?competSport) || ?competSport = wd:Q5849)           # Q5849=Rugby Union (keep sport-less and rugby affiliations)
  
  ?player wdt:P106 wd:Q14089670;                                     # P106=occupation, Q14089670=Rugby Union player
          wdt:P54 ?club.                                             # P54=member of sport team
    
  
  
  
  # name / sex
  OPTIONAL{?player wdt:P735 ?firstname.}                        # P735=given name
  OPTIONAL{?player wdt:P734 ?lastname.}                         # P734=family name
  OPTIONAL{?player wdt:P21 ?sex.}                               # P21=sex or gender
  
  # date/place of birth/death
  OPTIONAL{?player wdt:P569 ?dob.}                              # P569=date of birth
  OPTIONAL{?player wdt:P19 ?pob.}                               # P19=place of birth
  OPTIONAL{?player wdt:P570 ?dod.}                              # P570=date of death
  OPTIONAL{?player wdt:P20 ?pod.}                               # P20=place of death
  
  # countries & positions
  OPTIONAL{?player wdt:P27 ?citizenship.}                       # P27=country of citizenship
  OPTIONAL{?player wdt:P1532 ?sportCountry.}                    # P1532=country for sport
  OPTIONAL{?player wdt:P413 ?position.}                         # PP413=position played on team
  
  # career start/end dates
  OPTIONAL{?player wdt:P2031 ?careerStart.                      # P2031=work period (start)
           BIND(STR(YEAR(?careerStart)) AS ?careerStartYear)}
  OPTIONAL{?player wdt:P2032 ?careerEnd.                        # P2032=work period (end)
           BIND(STR(YEAR(?careerEnd)) AS ?careerEndYear)}
  
  # physical attributes
  OPTIONAL{?player wdt:P2067 ?mass.}                            # P2067=mass
  OPTIONAL{?player wdt:P2048 ?height.}                          # P2048=height
  
  # external IDs
  OPTIONAL{?player wdt:P858 ?ESPNscrumID.}                      # P858=ESPN Scrum international player ID
  OPTIONAL{?player wdt:P9903 ?AllRugbyID.}                      # P9903=All.Rugby player ID
  OPTIONAL{?player wdt:P2671 ?GoogleKnowlID.}                   # P2671=Google Knowledge Graph ID
  OPTIONAL{?player wdt:P3769 ?ItsRugbyID.}                      # P3769=It's Rugby player ID
  OPTIONAL{?player wdt:P12335 ?RugbyDatabaseID.}                # P12335=Rugby Database player ID
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". 
                           ?player rdfs:label ?playerLabel.
                           ?firstname rdfs:label ?firstnameLabel.
                           ?lastname rdfs:label ?lastnameLabel.
                           ?sex rdfs:label ?sexLabel.
                           ?pob rdfs:label ?pobLabel.
                           ?pod rdfs:label ?podLabel.
                           ?citizenship rdfs:label ?citizenshipLabel.
                           ?sportCountry rdfs:label ?sportCountryLabel.
                           ?position rdfs:label ?positionLabel.
                         } # just to get the label right
}
GROUP BY ?player ?playerLabel ?sexLabel ?dobFormat ?dodFormat
ORDER BY ?player 
