SELECT DISTINCT 
  ?player ?playerLabel
  ?club ?clubLabel 
  (STR(YEAR(?startDate)) AS ?startYear)
  (STR(YEAR(?endDate)) AS ?endYear)
  ?played
  ?points
WHERE
{ #BIND(wd:Q3547810 AS ?player)
  
  # list of players
  ?player wdt:P106 wd:Q14089670;            # P106=occupation, Q14089670=Rugby Union player
          wdt:P54 wd:Q599903.	            # P54=member of sports team, Q599903=Ireland national rugby union team
  
  # their club contracts
  ?player p:P54 ?statement.                 # P54=member of sports team, statement=relation between player/club
  ?statement ps:P54 ?club.                  # ps:=object of the relation, pq:=qualifier of the relation
  ?club wdt:P31 wd:Q43009164.	            # P31=instance of, Q43009164=Rugby union club >> disabling this line means retrieving junior clubs and international teams
  OPTIONAL{?statement pq:P580 ?startDate;}  # P580=start time
  OPTIONAL{?statement pq:P582 ?endDate.}    # P582=end time
  OPTIONAL{?statement pq:P1350 ?played.}    # P1350=number of matches played
  OPTIONAL{?statement pq:P1351 ?points.}    # P1351=number of points/goals/set scored
 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". } # just to get the label right
}
ORDER BY ?player ?startYear
