SELECT DISTINCT ?player ?playerLabel
  (GROUP_CONCAT(DISTINCT ?firstnameLabel; SEPARATOR=", ") as ?firstnameLabels)
  (GROUP_CONCAT(DISTINCT ?lastnameLabel; SEPARATOR=", ") as ?lastnameLabels)
  ?sexLabel 
  (MAX(?dob) AS ?dobMax) (CONCAT(STR(YEAR(?dobMax)),"-",STR(MONTH(?dobMax)),"-",STR(DAY(?dobMax))) AS ?dobFormat)
  (GROUP_CONCAT(DISTINCT ?pobLabel; SEPARATOR=", ") AS ?pobLabels)
  (MAX(?dod) AS ?dodMax) (CONCAT(STR(YEAR(?dodMax)),"-",STR(MONTH(?dodMax)),"-",STR(DAY(?dodMax))) AS ?dodFormat)
  (GROUP_CONCAT(DISTINCT ?podLabel; SEPARATOR=", ") AS ?podLabels)
  (GROUP_CONCAT(DISTINCT ?citizenshipLabel; SEPARATOR=", ") AS ?citizenshipLabels)
  (GROUP_CONCAT(DISTINCT ?sportCountryLabel; SEPARATOR=", ") AS ?sportCountryLabels)
  (GROUP_CONCAT(DISTINCT ?positionLabel; SEPARATOR=", ") AS ?positionLabels)
  ?careerStart ?careerEnd
  ?mass ?height
  ?ESPNscrumID ?AllRugbyID ?GoogleKnowlID ?ItsRugbyID ?RugbyDatabaseID
WHERE
{
  ?player wdt:P106 wd:Q14089670;   # P106=occupation, Q14089670=Rugby Union player
          wdt:P54 wd:Q599903.	     # P54=member of sports team, Q599903=Ireland national rugby union team
  
  OPTIONAL{?player wdt:P735 ?firstname.}
  OPTIONAL{?player wdt:P734 ?lastname.}
  OPTIONAL{?player wdt:P21 ?sex.}
  OPTIONAL{?player wdt:P569 ?dob.}
  OPTIONAL{?player wdt:P19 ?pob.}
  OPTIONAL{?player wdt:P570 ?dod.}
  OPTIONAL{?player wdt:P20 ?pod.}
  OPTIONAL{?player wdt:P27 ?citizenship.}
  OPTIONAL{?player wdt:P1532 ?sportCountry.}
  OPTIONAL{?player wdt:P413 ?position.}
  OPTIONAL{?player wdt:P2031 ?careerStart.}
  OPTIONAL{?player wdt:P2032 ?careerEnd.}
  OPTIONAL{?player wdt:P2067 ?mass.}
  OPTIONAL{?player wdt:P2048 ?height.}
  OPTIONAL{?player wdt:P858 ?ESPNscrumID.}
  OPTIONAL{?player wdt:P9903 ?AllRugbyID.}
  OPTIONAL{?player wdt:P2671 ?GoogleKnowlID.}
  OPTIONAL{?player wdt:P3769 ?ItsRugbyID.}
  OPTIONAL{?player wdt:P12335 ?RugbyDatabaseID.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". 
                           ?player rdfs:label ?playerLabel.
                           ?firstname rdfs:label ?firstnameLabel.
                           ?lastname rdfs:label ?lastnameLabel.
                           ?sex rdfs:label ?sexLabel.
                           ?pob rdfs:label ?pobLabel.
                           ?pod rdfs:label ?podLabel.
                           ?citizenship rdfs:label ?citizenshipLabel.
                           ?sportCountry rdfs:label ?sportCountryLabel.
                           ?position rdfs:label ?positionLabel.
                         } # just to get the label right
}
GROUP BY ?player ?playerLabel ?sexLabel ?dobFormat ?dodFormat ?careerStart ?careerEnd ?mass ?height ?ESPNscrumID ?AllRugbyID ?GoogleKnowlID ?ItsRugbyID ?RugbyDatabaseID
