########################################################################
# This query retrieves the list of all the rugby union teams described
# on Wikidata.
#
# Vincent Labatut
# 12/2024
########################################################################

SELECT DISTINCT ?team ?teamId

WHERE
{ 
  ############# constraints on the rugby teams
  # get the rugby teams (more general category)
  {    
    ?team wdt:P31 wd:Q14645593.                                     # P31=instance of, Q14645593=Rugby union team
  }
  UNION
  # add the teams, clubs and franchises (more specific categories)
  {
    ?team wdt:P31/wdt:P279* wd:Q14645593.                           # P31=instance of, P279=subclass of, Q14645593=Rugby union team
  }
  # filter depending on team type
  ?team wdt:P31 ?teamType.                                          # P31=instance of
  FILTER(?teamType IN(
                      wd:Q14645593,                                 # Q14645593=rugby union team
                      wd:Q43009164,                                 # Q43009164=rugby union club
                      wd:Q63171169,                                 # Q63171169=rugby union franchise
                      wd:Q63171186,                                 # Q63171186=defunct rugby union club
#                     wd:Q113144812,                                # Q113144812=women's rugby union club
                      wd:Q58840819,                                 # Q58840819=national rugby union team
                      wd:Q104630756                                 # Q104630756=second rugby union team
                    ))
  
  # keep only the Wikidata ID (not the whole URL)
  BIND(STRAFTER(STR(?team), STR(wd:)) AS ?teamId).
  
}

ORDER BY ?teamId
